# Generated by Django 4.2.2 on 2023-06-17 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.rol'),
        ),
    ]
