# Generated by Django 4.2.2 on 2023-06-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, default='static/images/basic_avatar.svg', max_length=500, null=True),
        ),
    ]
