# Generated by Django 4.2.2 on 2023-06-17 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_category_article_article_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='contrasena',
            new_name='password',
        ),
    ]
